Added a line on 15th Feb 2025 for testing in Git Hub

**In order to read any datafile, we need below**

- where is the file $located$

- what is the file $name$

- what is the file $extension$

- $**Note**: Anaconda3 software also should be in the same drive where file is location$

Sample check
- File Location:
C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files

- File name:
SkillNation1

- File extension:
.xlsx

In [9]:
'C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\SkillNation1.xlsx'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (268027899.py, line 1)

**unicode error**

- unicode error appears in the local machines not on cloud platforms

- unicode means we provide **single slash**

- in order to avoid that we need to provide **double slash**

- or we can give a letter 'r' before starting of the file name
    - 'r' indicates **raw string**

In [14]:
'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\SkillNation1.xlsx'

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\SkillNation1.xlsx'

In [18]:
r'C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\SkillNation1.xlsx'

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\SkillNation1.xlsx'

In [20]:
r"C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\Data_in_Pic.png"

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Data_in_Pic.png'

In [22]:
r"C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\Statement of Encumbrance on Property - Rampally Plot 21 Survey 416-25Mar2023_2.pdf"

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Statement of Encumbrance on Property - Rampally Plot 21 Survey 416-25Mar2023_2.pdf'

In [24]:
r"C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\Color Combinations.docx"

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Color Combinations.docx'

In [26]:
r"D:\Nagaraj AG\Others\Nagaraj AG - Covaxin Second Dose Certificate.pdf"

'D:\\Nagaraj AG\\Others\\Nagaraj AG - Covaxin Second Dose Certificate.pdf'

**How to read the file**

In [33]:
file_location='C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\SkillNation1.xlsx'
open(file_location)

In [53]:
import pandas as pd
file_location='C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Workshop Data_Nag1.xlsx'
#data1=pd.read_excel(file_location)
#print(data1)
pd.read_excel(file_location)

,State,Customer Name,Revenue,Unnamed: 3,Find all customers & it's revenue from the state:,Unnamed: 5,Unnamed: 6,Delhi,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Latest Formulas in O365:
0,Punjab,Rahul Shah,44196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XLOOKUP
1,Maharashtra,Payal Mehta,20898,NaN,Option #1 - Vlookup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FILTER
2,Kerala,Rita Shah,46994,NaN,State,Customer Name,Revenue,NaN,NaN,NaN,NaN,NaN,UNIQUE
3,Gujrat,Neha Mishra,43695,NaN,Delhi,Tanvi Sharma,34196,NaN,NaN,NaN,NaN,NaN,SORT & SORTBY
4,Delhi,Tanvi Sharma,34196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEXTSPLIT
5,Punjab,Kanci Nagori,34155,NaN,Option #2 - Filter Manually,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEXTBEFORE
6,Maharashtra,Rita Mishra,24396,NaN,State,Customer Name,Revenue,NaN,NaN,NaN,NaN,NaN,TEXTAFTER
7,Kerala,Harshit Shah,29276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VSTACK
8,Gujrat,Mehul Mehta,45540,NaN,Option #3 - The new Filter formula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HSTACK
9,Delhi,Bhumi Shah,29277,NaN,State,Customer Name,Revenue,NaN,NaN,NaN,NaN,NaN,CHOOSECOLS
10,Punjab,Riya Sanghavi,44675,NaN,Delhi,Tanvi Sharma,34196,NaN,(Filter 1)*(Filter 2),NaN,NaN,NaN,CHOOSEROWS
11,Maharashtra,Manish Desai,42569,NaN,Delhi,Bhumi Shah,29277,NaN,NaN,NaN,NaN,NaN,DROP
12,Kerala,Hitendra Khan,43784,NaN,Delhi,Dipesh Shah,49656,NaN,NaN,NaN,NaN,NaN,TAKE
13,Gujrat,Bharat Kapoor,46336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EXPAND
14,Delhi,Dipesh Shah,49656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOCOL
15,Gujrat,Kanan Somaiya,61574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOROW
16,Kerala,Karan Kapoor,66500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WRAPCOLS
17,Maharashtra,Tina Mehta,55195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WRAPROWS
18,Punjab,Krystal Shah,45260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MINIFS
19,Kerala,Kirit Khan,59291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IFS
20,Gujrat,Kushal Desai,44469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAXIFS
21,Kerala,Tina Mishra,33797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Maharashtra,Mahesh Chaudhary,31770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Punjab,Rajkumar Yadav,34630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Gujrat,Aryan Tripathi,42249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Gujrat,Leena Dias,34222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Kerala,Sachin Bansal,45174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Maharashtra,Karan Vyas,37495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Punjab,Nandini Maheshwari,30746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
r"C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\Workshop Data_Nag1.xlsx"

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Workshop Data_Nag1.xlsx'

In [55]:
r"C:\Users\Nagaraj AG\OneDrive\Desktop\Temp Files\Python Assignment - 4Jan2025.txt"

'C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Python Assignment - 4Jan2025.txt'

In [66]:
filename='C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Python Assignment - 4Jan2025.txt'
file1=open(filename)
data2=file1.read()
print(data2)

# 1)wap ask the user enter 3 numbers n1,n2,n3 from ketboard
# calculate average

n1=input("Enter first number")
n2=input("Enter second number")
n3=input("Enter third number")
avg1=(eval(n1)+eval(n2)+eval(n3))/3
print(f"The average of first, second and third numbers is {avg1}")

***************

# 2)wap ask the user enter name age city
# print my name is python im 10 years old and came from hyd

a=input("Enter your Name:")
b=input("Enter your Age:")
c=input('Enter your City:')
print(f"My name is {a}, age is {b} and came from {c}")

***************

# 3)wap ask the user to enter radidus of a circle calculate area of the circle
# var: radidus  var: pi=3.14
# formuale: pi*radius*radius
# print the answers using f string and format

r=input("Enter the radius of the circle")
pi=22/7
print("pi value is considered as 22/7 i.e., 3.14")
ar=round(eval(r)*eval(r)*pi,5)
print(f"The Area of the circle whose radius {r} is {ar}")

******************

# 4)wap ask the user enter breadth and height of a right angle triangle
# calculate the area
# var1: bredath  var2: height
# formuale : 0.5*breadth*heigh

h=input("Enter the Height of the Right Angled Triangle:")
b=input("Enter the Base of the Right Angled Triangle:")
ar2=round((1/2)*eval(h)*eval(b),5)
print(f"Area of Right Angled Triangle is 0.5 x Height x Base that is {ar2}")

*********************

# 5)wap ask the user the bill amount and tip amount
#   calculate total bill
#   var1: bill amount var2: tip amount
#   formuale
bill=input('please enter your bill amount:')
tip=input('please enter the tip amount:')
totamt=round(eval(bill)+eval(tip),2)
print(f'Total Amount payable by you is: {bill} + {tip} = {totamt}/-')

***********

# 6)wap ask the user the bill amount and tip percentage
#    take tip percentage as 10
#   calculate total bill= bill amount+ bill amount*tip per/100
#   var1: bill amount var2: tip amount
#    formuale
bill2=input('please enter your bill amount:')
tip2=eval(bill2)*10/100
totamt2=round(eval(bill2)+tip2,2)
print(f'Total Amount payable by you with 10% tip is: {bill2} + {tip2} = {totamt2}/-')

***************

# 7)wap ask the length and breadth of a rectangle calculate area
#   var1: length  var2: breadth
#   formulae: length * breadth

ln=input('Enter length of the Rectangle:')
br=input('Enter breadth of the Rectangle:')
per=round(2*(eval(ln)+eval(br)),5)
ar3=round(eval(ln)*eval(br),3)
print(f'If {ln} and {br} are length and breadth of a Rectangle then its Area is {ar3} and its Perimeter is {per}')

******************

# 8) wap ask the user take the radius and calculate volume of sphere
#   formulae: pi*r**3(pi*r*r*r)

r3=input('Enter Radius of the Sphere:')
vol=round((4/3)*(22/7)*eval(r3)*eval(r3)*eval(r3),4)
print(f'Volume of a Sphere with radius {r3} is {vol}')

************

# 9) wap ask the user enter amount in dollars convert into rupees
#     1$=85rs

usd=input('Please enter the amount in dollars:')
inr=round(eval(usd)*85,3)
print(f"You have {inr} in Indian Rupee")

**Common Errors**

- Unicode error: due to single slash
    - provide double slash or apply r (raw string)

- file not found error
    - either wrong location or spell mistake

- permission denied error
    - due to the file is already opened
    - close that file and read it again

In [64]:
open('C:\\Users\\Nagaraj AG\\OneDrive\\Desktop\\Temp Files\\Python Assignment - 4Jan2025.txt').read()

'# 1)wap ask the user enter 3 numbers n1,n2,n3 from ketboard\n# calculate average\n\nn1=input("Enter first number")\nn2=input("Enter second number")\nn3=input("Enter third number")\navg1=(eval(n1)+eval(n2)+eval(n3))/3\nprint(f"The average of first, second and third numbers is {avg1}")\n\n***************\n\n# 2)wap ask the user enter name age city\n# print my name is python im 10 years old and came from hyd\n\na=input("Enter your Name:")\nb=input("Enter your Age:")\nc=input(\'Enter your City:\')\nprint(f"My name is {a}, age is {b} and came from {c}")\n\n***************\n\n# 3)wap ask the user to enter radidus of a circle calculate area of the circle\n# var: radidus  var: pi=3.14\n# formuale: pi*radius*radius\n# print the answers using f string and format\n\nr=input("Enter the radius of the circle")\npi=22/7\nprint("pi value is considered as 22/7 i.e., 3.14")\nar=round(eval(r)*eval(r)*pi,5)\nprint(f"The Area of the circle whose radius {r} is {ar}")\n\n******************\n\n# 4)wap ask the user enter breadth and height of a right angle triangle\n# calculate the area\n# var1: bredath  var2: height\n# formuale : 0.5*breadth*heigh\n\nh=input("Enter the Height of the Right Angled Triangle:")\nb=input("Enter the Base of the Right Angled Triangle:")\nar2=round((1/2)*eval(h)*eval(b),5)\nprint(f"Area of Right Angled Triangle is 0.5 x Height x Base that is {ar2}")\n\n*********************\n\n# 5)wap ask the user the bill amount and tip amount\n#   calculate total bill\n#   var1: bill amount var2: tip amount\n#   formuale\nbill=input(\'please enter your bill amount:\')\ntip=input(\'please enter the tip amount:\')\ntotamt=round(eval(bill)+eval(tip),2)\nprint(f\'Total Amount payable by you is: {bill} + {tip} = {totamt}/-\')\n\n***********\n\n# 6)wap ask the user the bill amount and tip percentage\n#    take tip percentage as 10\n#   calculate total bill= bill amount+ bill amount*tip per/100\n#   var1: bill amount var2: tip amount\n#    formuale\nbill2=input(\'please enter your bill amount:\')\ntip2=eval(bill2)*10/100\ntotamt2=round(eval(bill2)+tip2,2)\nprint(f\'Total Amount payable by you with 10% tip is: {bill2} + {tip2} = {totamt2}/-\')\n\n***************\n\n# 7)wap ask the length and breadth of a rectangle calculate area\n#   var1: length  var2: breadth\n#   formulae: length * breadth\n\nln=input(\'Enter length of the Rectangle:\')\nbr=input(\'Enter breadth of the Rectangle:\')\nper=round(2*(eval(ln)+eval(br)),5)\nar3=round(eval(ln)*eval(br),3)\nprint(f\'If {ln} and {br} are length and breadth of a Rectangle then its Area is {ar3} and its Perimeter is {per}\')\n\n******************\n\n# 8) wap ask the user take the radius and calculate volume of sphere\n#   formulae: pi*r**3(pi*r*r*r)\n\nr3=input(\'Enter Radius of the Sphere:\')\nvol=round((4/3)*(22/7)*eval(r3)*eval(r3)*eval(r3),4)\nprint(f\'Volume of a Sphere with radius {r3} is {vol}\')\n\n************\n\n# 9) wap ask the user enter amount in dollars convert into rupees\n#     1$=85rs\n\nusd=input(\'Please enter the amount in dollars:\')\ninr=round(eval(usd)*85,3)\nprint(f"You have {inr} in Indian Rupee")\n\n\n\n\n\n\n\n'

In [70]:
# method 2
with open(filename) as file:
    data2=file.read()
print(data2)

# 1)wap ask the user enter 3 numbers n1,n2,n3 from ketboard
# calculate average

n1=input("Enter first number")
n2=input("Enter second number")
n3=input("Enter third number")
avg1=(eval(n1)+eval(n2)+eval(n3))/3
print(f"The average of first, second and third numbers is {avg1}")

***************

# 2)wap ask the user enter name age city
# print my name is python im 10 years old and came from hyd

a=input("Enter your Name:")
b=input("Enter your Age:")
c=input('Enter your City:')
print(f"My name is {a}, age is {b} and came from {c}")

***************

# 3)wap ask the user to enter radidus of a circle calculate area of the circle
# var: radidus  var: pi=3.14
# formuale: pi*radius*radius
# print the answers using f string and format

r=input("Enter the radius of the circle")
pi=22/7
print("pi value is considered as 22/7 i.e., 3.14")
ar=round(eval(r)*eval(r)*pi,5)
print(f"The Area of the circle whose radius {r} is {ar}")

******************

# 4)wap ask the user enter breadth and height of a right angle triangle
# calculate the area
# var1: bredath  var2: height
# formuale : 0.5*breadth*heigh

h=input("Enter the Height of the Right Angled Triangle:")
b=input("Enter the Base of the Right Angled Triangle:")
ar2=round((1/2)*eval(h)*eval(b),5)
print(f"Area of Right Angled Triangle is 0.5 x Height x Base that is {ar2}")

*********************

# 5)wap ask the user the bill amount and tip amount
#   calculate total bill
#   var1: bill amount var2: tip amount
#   formuale
bill=input('please enter your bill amount:')
tip=input('please enter the tip amount:')
totamt=round(eval(bill)+eval(tip),2)
print(f'Total Amount payable by you is: {bill} + {tip} = {totamt}/-')

***********

# 6)wap ask the user the bill amount and tip percentage
#    take tip percentage as 10
#   calculate total bill= bill amount+ bill amount*tip per/100
#   var1: bill amount var2: tip amount
#    formuale
bill2=input('please enter your bill amount:')
tip2=eval(bill2)*10/100
totamt2=round(eval(bill2)+tip2,2)
print(f'Total Amount payable by you with 10% tip is: {bill2} + {tip2} = {totamt2}/-')

***************

# 7)wap ask the length and breadth of a rectangle calculate area
#   var1: length  var2: breadth
#   formulae: length * breadth

ln=input('Enter length of the Rectangle:')
br=input('Enter breadth of the Rectangle:')
per=round(2*(eval(ln)+eval(br)),5)
ar3=round(eval(ln)*eval(br),3)
print(f'If {ln} and {br} are length and breadth of a Rectangle then its Area is {ar3} and its Perimeter is {per}')

******************

# 8) wap ask the user take the radius and calculate volume of sphere
#   formulae: pi*r**3(pi*r*r*r)

r3=input('Enter Radius of the Sphere:')
vol=round((4/3)*(22/7)*eval(r3)*eval(r3)*eval(r3),4)
print(f'Volume of a Sphere with radius {r3} is {vol}')

************

# 9) wap ask the user enter amount in dollars convert into rupees
#     1$=85rs

usd=input('Please enter the amount in dollars:')
inr=round(eval(usd)*85,3)
print(f"You have {inr} in Indian Rupee")

**method 3**

- if python file and the data file are in different locations, then we need full path

- but if python file and datafile both are in same location then we need simply the file name

In [78]:
import os
os.getcwd()

'C:\\Users\\Nagaraj AG\\Documents\\NareshIT\\Python_Sessions'

In [3]:
print(open('Testing_File_14Feb25.txt').read())

This is a test txt file.
You are able to view this message

In [35]:
file_location='Testing_File_14Feb25.txt'
filename=open(file_location, mode='w')

filename.write('adding a comment using python')
filename=open(file_location, mode='r')
text1=filename.read()
print(text1)

adding a comment using python

In [39]:
file_location='Testing_File_14Feb25.txt'
filename=open(file_location, mode='x')

filename.write('adding a comment using python')
filename=open(file_location, mode='r')
text1=filename.read()
print(text1)

FileExistsError: [Errno 17] File exists: 'Testing_File_14Feb25.txt'